// __tests__/golden-path-parent.test.js
// ────────────────────────────────────────────────────────
// End-to-end parent journey on an ephemeral Postgres
// via testcontainers (mirrors golden-path-admin pattern).
// ────────────────────────────────────────────────────────

const request = require('supertest');
const { PostgreSqlContainer } = require('@testcontainers/postgresql');
const { execSync } = require('child_process');
const bcrypt = require('bcryptjs');

let app, prisma, postgresContainer;

// Tokens
let superAdminToken, schoolAdminToken, parentToken;

// Seed identifiers
const superAdminEmail = `super.parent.${Date.now()}@test.com`;
const schoolAdminEmail = `admin.parent.${Date.now()}@test.com`;
let parentEmail; // auto-generated by createStudent
let onboarded = { schoolId: null, classId: null, academicYearId: null };
let studentId;

jest.setTimeout(60000);

beforeAll(async () => {
    // 1. Ephemeral Postgres
    postgresContainer = await new PostgreSqlContainer('postgres:15-alpine')
        .withDatabase('school_system')
        .withUsername('user')
        .withPassword('password')
        .start();

    process.env.DATABASE_URL = postgresContainer.getConnectionUri();
    process.env.PORT = '0';

    // 2. Hydrate schema
    execSync('npx prisma db push --skip-generate', { env: process.env, stdio: 'inherit' });

    // 3. Import app + prisma
    app = require('../index');
    prisma = require('../src/prismaClient');

    // 4. Seed super_admin
    const hash = await bcrypt.hash('SuperPass123!', 10);
    await prisma.user.create({
        data: {
            fullName: 'Golden Super Admin',
            email: superAdminEmail,
            role: 'super_admin',
            password_hash: hash,
            isActive: true,
            emailVerified: true,
        },
    });
});

afterAll(async () => {
    if (prisma) await prisma.$disconnect();
    if (postgresContainer) await postgresContainer.stop();
});

describe('Golden Path: Parent E2E Journey', () => {

    // ── Setup steps (admin side) ──────────────────

    it('Step 1: Super Admin logs in', async () => {
        const res = await request(app)
            .post('/api/auth/login')
            .send({ email: superAdminEmail, password: 'SuperPass123!' });

        expect(res.status).toBe(200);
        expect(res.body.success).toBe(true);
        superAdminToken = res.body.data.token;
    });

    it('Step 2: Onboard school with class', async () => {
        const res = await request(app)
            .post('/api/platform/onboard-school')
            .set('Authorization', `Bearer ${superAdminToken}`)
            .send({
                school: { name: `Parent Golden School ${Date.now()}`, city: 'Test City' },
                admin: { fullName: 'School Admin', email: schoolAdminEmail, password: 'AdminPass123!' },
                academicYear: { name: '2030-2031', startDate: '2030-09-01', endDate: '2031-06-30', isCurrent: true },
                classes: [{ name: 'Class 1A', defaultFee: 500 }],
            });

        expect(res.status).toBe(200);
        expect(res.body.success).toBe(true);
        onboarded.schoolId = res.body.data.schoolId;
        onboarded.classId = res.body.data.classIds[0];
        onboarded.academicYearId = res.body.data.academicYearId;
    });

    it('Step 3: School Admin logs in', async () => {
        const res = await request(app)
            .post('/api/auth/login')
            .send({ email: schoolAdminEmail, password: 'AdminPass123!' });

        expect(res.status).toBe(200);
        schoolAdminToken = res.body.data.token;
    });

    it('Step 4: Admin creates student (auto-creates parent)', async () => {
        const res = await request(app)
            .post('/api/school/students')
            .set('Authorization', `Bearer ${schoolAdminToken}`)
            .send({
                fullName: 'Golden Child',
                classId: onboarded.classId,
                parentEmail: `parent.golden.${Date.now()}@test.com`,
            });

        expect(res.status).toBe(201);
        expect(res.body.success).toBe(true);
        studentId = res.body.data.student.id;

        // Discover the auto-generated parent email
        const student = await prisma.student.findUnique({
            where: { id: studentId },
            include: { parent: { select: { email: true } } },
        });
        parentEmail = student.parent.email;
    });

    it('Step 5: Admin submits attendance for the student', async () => {
        const today = new Date().toISOString().slice(0, 10);
        const res = await request(app)
            .post('/api/attendance/bulk')
            .set('Authorization', `Bearer ${schoolAdminToken}`)
            .send({
                classId: onboarded.classId,
                date: today,
                records: [{ studentId, status: 'present' }],
            });

        expect(res.status).toBe(200);
        expect(res.body.success).toBe(true);
    });

    // ── Parent journey ────────────────────────────

    it('Step 6: Parent logs in', async () => {
        const res = await request(app)
            .post('/api/auth/login')
            .send({ email: parentEmail, password: 'password123' });

        expect(res.status).toBe(200);
        expect(res.body.success).toBe(true);
        parentToken = res.body.data.token;
    });

    it('Step 7: GET /api/students/my-children returns at least 1 child', async () => {
        const res = await request(app)
            .get('/api/students/my-children')
            .set('Authorization', `Bearer ${parentToken}`);

        expect(res.status).toBe(200);
        expect(res.body.success).toBe(true);
        expect(res.body.data.length).toBeGreaterThanOrEqual(1);
    });

    it('Step 8: GET /api/parent/attendance/:studentId returns 200 with records+summary', async () => {
        const res = await request(app)
            .get(`/api/parent/attendance/${studentId}`)
            .set('Authorization', `Bearer ${parentToken}`);

        expect(res.status).toBe(200);
        expect(res.body.success).toBe(true);
        expect(res.body.data).toHaveProperty('records');
        expect(res.body.data).toHaveProperty('summary');
        expect(Array.isArray(res.body.data.records)).toBe(true);
    });

    it('Step 9: GET /api/academics/homework?studentId=... returns 200', async () => {
        const res = await request(app)
            .get(`/api/academics/homework?studentId=${studentId}`)
            .set('Authorization', `Bearer ${parentToken}`);

        expect(res.status).toBe(200);
        expect(res.body.success).toBe(true);
        expect(Array.isArray(res.body.data)).toBe(true);
    });

    it('Step 10: GET /api/parent/invoices/:studentId returns 200 with invoices', async () => {
        const res = await request(app)
            .get(`/api/parent/invoices/${studentId}`)
            .set('Authorization', `Bearer ${parentToken}`);

        expect(res.status).toBe(200);
        expect(res.body.success).toBe(true);
        expect(res.body.data).toHaveProperty('invoices');
        expect(Array.isArray(res.body.data.invoices)).toBe(true);
    });
});
